// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Web.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieApp.Web.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20231120082945_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.Web.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Matt Eskandari is an Iranian-born American film director and screenwriter. His films include Victim, The Gauntlet, and 12 Feet Deep. He was also a contestant on the Fox Studios and Steven Spielberg filmmaker competition On the Lot.",
                            ImageUrl = "d1.jpg",
                            Name = "Matt Eskandari"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Zoe Lister-Jones is an American actress and filmmaker who co-starred as Jen Collins Short in the CBS sitcom Life in Pieces from 2015 to 2019. She is also known for her roles in the television shows Delocated, Whitney, and New Girl. Lister-Jones made her directorial debut with the 2017 comedy-drama film Band Aid.",
                            ImageUrl = "d2.jpeg",
                            Name = "Zoe Lister-Jones"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Christopher Edward Nolan CBE is a British and American filmmaker. Known for his Hollywood blockbusters with complex storytelling, Nolan is considered a leading filmmaker of the 21st century. His films have grossed more than $6 billion worldwide.",
                            ImageUrl = "d3.jpeg",
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Christopher Kip Forbes is vice chairman of the Forbes Publishing company. He attended St. Mark's School in Southborough, Massachusetts, and Princeton University. His brother is Steve Forbes, who has made multiple runs for the U.S. presidency and written some in-depth political and economic narratives.",
                            ImageUrl = "d4.jpg",
                            Name = "Christopher Forbes"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Writers/Directors Eshom and Ian Nelms, grew up in central California waging two hundred man G.I. Joe wars and dreaming in John Ford Landscapes. Though their evolving passions temporarily took them in different directions - Ian went to college on a wrestling scholarship, along the way discovering a new interest for English and Literature, and Eshom pursued an education in fine art painting, but found the illustration of comic books better suited to his tastes - the two would always find themselves returning to their love of film. While Ian has produced various projects independently and Eshom has worked as a professional storyboard artist for over a decade, the Nelms Brothers always write and direct together and have made multiple award-winning short and feature films.",
                            ImageUrl = "d5.jpg",
                            Name = "Eshom Nelms"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Logothetis was born in Athens, Greece,[3] and immigrated to the United States of America at the age of six with his mother, Anna, and his father, Euthymios. Euthymios moved to the United States to join his family, spending eight years working as a mechanic in Los Angeles and becoming an American citizen.",
                            ImageUrl = "d6.jpg",
                            Name = "Dimitri Logothetis"
                        });
                });

            modelBuilder.Entity("MovieApp.Web.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Romantik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Komedi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Macera"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Savaş"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Animasyon"
                        });
                });

            modelBuilder.Entity("MovieApp.Web.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DirectorId")
                        .HasColumnType("integer");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Every six years, an ancient order of jiu-jitsu fighters joins forces to battle a vicious race of alien invaders. But when a celebrated war hero goes down in defeat, the fate of the planet and mankind hangs in the balance.",
                            DirectorId = 6,
                            GenreId = 4,
                            ImageUrl = "jiujitsu.jpg",
                            Title = "Jiu Jitsu"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A rowdy, unorthodox Santa Claus is fighting to save his declining business. Meanwhile, Billy, a neglected and precocious 12 year old, hires a hit man to kill Santa after receiving a lump of coal in his stocking.",
                            DirectorId = 5,
                            GenreId = 2,
                            ImageUrl = "fatman.jpg",
                            Title = "Fatman"
                        },
                        new
                        {
                            Id = 3,
                            Description = "When their brother is killed by an outlaw, three Dalton brothers join their sheriff's dept. When they're cheated by the law, they turn to crime. Trying to outdo Jesse James, they try to rob two banks at once in 1892. Things get ugly.",
                            DirectorId = 4,
                            GenreId = 4,
                            ImageUrl = "tdaltong.jpg",
                            Title = "The Dalton Gang"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
                            DirectorId = 3,
                            GenreId = 4,
                            ImageUrl = "tenet.jpg",
                            Title = "Tenet"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A group of high school students form a coven of witches.",
                            DirectorId = 2,
                            GenreId = 3,
                            ImageUrl = "tcraft.jpg",
                            Title = "Film 5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The work of billionaire tech CEO Donovan Chalmers (Willis) is so valuable that he hires mercenaries to protect it, and a terrorist group kidnaps his daughter just to get it.",
                            DirectorId = 1,
                            GenreId = 3,
                            ImageUrl = "hardkill.jpeg",
                            Title = "Hard Kill"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
